cd "D:\CoP\src\eg\edu\alexu\csd\oop\game";
cd controller;
git pull -f origin controller:controller;
cd ..;
cd examples;
git pull -f origin examples:examples;
cd ..;
cd model;
git pull -f origin model:model;
cd ..;
cmd /k command;